import React from "react";
import Layout from "../components/Layout";

const TermsPage: React.FC = () => {
  return (
    <Layout>
      <section className="mb-6 rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-700">
        <h1 className="text-2xl font-semibold text-slate-900 mb-3">
          Terms of Use
        </h1>

        <p className="mt-2">
          Welcome to <strong>PDFConvert.tech</strong>. By accessing or using this
          website and our tools, you agree to be bound by these Terms of Use. If
          you do not agree, please do not use this service.
        </p>

        <h2 className="mt-4 font-semibold text-slate-900">
          1. Acceptable Use
        </h2>
        <p className="mt-1">
          You agree to use our tools only for legal, ethical and educational
          purposes. You must not use this website to:
        </p>
        <ul className="mt-2 list-disc pl-5 space-y-1">
          <li>Violate any applicable laws or regulations.</li>
          <li>Upload, share or process illegal, harmful or abusive content.</li>
          <li>Attempt to hack, overload, scrape or disrupt the service.</li>
        </ul>

        <h2 className="mt-4 font-semibold text-slate-900">
          2. Your Responsibility
        </h2>
        <p className="mt-1">
          You are fully responsible for the files you upload and any output
          generated by the tools. We do not review or monitor the content of
          your files and we do not provide legal advice regarding their use.
        </p>

        <h2 className="mt-4 font-semibold text-slate-900">
          3. Cookies and Analytics
        </h2>
        <p className="mt-1">
          We may use cookies and third-party analytics or advertising services
          to understand traffic, improve the website and display relevant ads.
          For more details, please read our{" "}
          <a href="/cookies" className="text-sky-600 underline">
            Cookies Policy
          </a>{" "}
          and{" "}
          <a href="/privacy" className="text-sky-600 underline">
            Privacy Policy
          </a>
          .
        </p>

        <h2 className="mt-4 font-semibold text-slate-900">
          4. No Warranty
        </h2>
        <p className="mt-1">
          The service is provided on an &quot;as is&quot; and &quot;as
          available&quot; basis. We do not guarantee that the tools will be
          error-free, uninterrupted or suitable for every purpose.
        </p>

        <h2 className="mt-4 font-semibold text-slate-900">
          5. Changes to These Terms
        </h2>
        <p className="mt-1">
          We may update these Terms of Use from time to time. Changes will
          become effective when posted on this page. Your continued use of the
          website after changes means you accept the updated terms.
        </p>

        <p className="mt-4 text-xs text-slate-500">
          This page is provided for general information and does not constitute
          legal advice.
        </p>
      </section>
    </Layout>
  );
};

export default TermsPage;
