import React from "react";
import { Link } from "react-router-dom";
import Layout from "../components/Layout";
import { Helmet } from "react-helmet";

const TermsPage: React.FC = () => {
  return (
    <Layout>
      <Helmet>
        <title>Terms of Service – PDFConvert.tech</title>
        <meta name="description" content="Terms of Service for PDFConvert.tech - Legal agreement and usage guidelines." />
      </Helmet>

      {/* ================================
          HERO HEADER - Enhanced
      ================================= */}
      <header className="text-center mb-12">
        <Link to="/" className="text-orange-600 hover:text-orange-700 font-semibold mb-4 inline-block">
          ← Back to Home
        </Link>

        <div className="inline-block mb-4 px-4 py-2 bg-orange-100 text-orange-700 rounded-full text-sm font-semibold">
          Legal Agreement
        </div>

        <h1 className="text-5xl md:text-6xl font-extrabold text-slate-900 tracking-tight mb-4">
          Terms of <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-500 to-orange-600">Service</span>
        </h1>

        <p className="text-xl md:text-2xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
          Please read these terms carefully. By using PDFConvert.tech, you agree to abide by these conditions.
        </p>
      </header>

      {/* ================================
          MAIN CONTENT - Professional Sections
      ================================= */}
      <div className="space-y-8">

        {/* Section 1 */}
        <section className="bg-white rounded-3xl p-8 md:p-12 shadow-md border border-orange-100">
          <div className="flex items-start gap-4 mb-6">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 mb-2">Acceptable Use</h2>
              <p className="text-gray-600">Guidelines for proper service usage</p>
            </div>
          </div>

          <div className="ml-0 md:ml-16 space-y-4">
            <p className="text-gray-700 leading-relaxed mb-4">
              You agree to use our tools only for legal, ethical, and lawful purposes. Prohibited activities include:
            </p>

            <div className="space-y-3">
              <div className="bg-gradient-to-r from-orange-50 to-amber-50 rounded-2xl p-6 border border-orange-100">
                <h3 className="font-semibold text-slate-900 mb-2">Violating Laws</h3>
                <p className="text-gray-700 text-sm">Using our service in violation of any applicable laws, regulations, or legal obligations.</p>
              </div>

              <div className="bg-gradient-to-r from-orange-50 to-amber-50 rounded-2xl p-6 border border-orange-100">
                <h3 className="font-semibold text-slate-900 mb-2">Illegal Content</h3>
                <p className="text-gray-700 text-sm">Uploading, processing, or sharing illegal, harmful, abusive, or defamatory content.</p>
              </div>

              <div className="bg-gradient-to-r from-orange-50 to-amber-50 rounded-2xl p-6 border border-orange-100">
                <h3 className="font-semibold text-slate-900 mb-2">Unauthorized Access</h3>
                <p className="text-gray-700 text-sm">Attempting to hack, overload, scrape, disrupt, or gain unauthorized access to our service.</p>
              </div>

              <div className="bg-gradient-to-r from-orange-50 to-amber-50 rounded-2xl p-6 border border-orange-100">
                <h3 className="font-semibold text-slate-900 mb-2">Intellectual Property</h3>
                <p className="text-gray-700 text-sm">Infringing upon copyrights, trademarks, or intellectual property rights of others.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 2 */}
        <section className="bg-white rounded-3xl p-8 md:p-12 shadow-md border border-orange-100">
          <div className="flex items-start gap-4 mb-6">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 mb-2">Your Responsibility</h2>
              <p className="text-gray-600">Understanding your obligations and liability</p>
            </div>
          </div>

          <div className="ml-0 md:ml-16 bg-gradient-to-r from-red-50 to-rose-50 rounded-2xl p-8 border border-red-100">
            <ul className="space-y-3">
              <li className="flex items-start gap-3">
                <span className="text-orange-600 font-bold text-lg mt-0.5">•</span>
                <span className="text-gray-700"><strong>Full Responsibility:</strong> You are entirely responsible for all files you upload and any output generated by our tools.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-orange-600 font-bold text-lg mt-0.5">•</span>
                <span className="text-gray-700"><strong>No Content Monitoring:</strong> We do not review, monitor, or filter the content of your files.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-orange-600 font-bold text-lg mt-0.5">•</span>
                <span className="text-gray-700"><strong>No Legal Advice:</strong> We do not provide legal advice regarding your files or their usage.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-orange-600 font-bold text-lg mt-0.5">•</span>
                <span className="text-gray-700"><strong>Compliance:</strong> You must ensure your use complies with all applicable laws and third-party rights.</span>
              </li>
            </ul>
          </div>
        </section>

        {/* Section 3 */}
        <section className="bg-white rounded-3xl p-8 md:p-12 shadow-md border border-orange-100">
          <div className="flex items-start gap-4 mb-6">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 mb-2">Analytics & Data Collection</h2>
              <p className="text-gray-600">How we collect and use information</p>
            </div>
          </div>

          <div className="ml-0 md:ml-16 space-y-4">
            <p className="text-gray-700 leading-relaxed mb-4">
              We use analytics and third-party services to improve our website and understand usage patterns. For complete details, please read our:
            </p>

            <div className="grid gap-4 md:grid-cols-2">
              <Link to="/privacy" className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl p-6 border border-blue-100 hover:shadow-lg transition-all">
                <h3 className="font-semibold text-slate-900 mb-2">Privacy Policy</h3>
                <p className="text-gray-700 text-sm">Learn how we collect, use, and protect your data.</p>
              </Link>
            </div>
          </div>
        </section>

        {/* Section 4 */}
        <section className="bg-white rounded-3xl p-8 md:p-12 shadow-md border border-orange-100">
          <div className="flex items-start gap-4 mb-6">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 mb-2">Service Warranty</h2>
              <p className="text-gray-600">Understanding service limitations and disclaimers</p>
            </div>
          </div>

          <div className="ml-0 md:ml-16 bg-gradient-to-r from-yellow-50 to-amber-50 rounded-2xl p-8 border border-yellow-100">
            <ul className="space-y-3">
              <li className="flex items-start gap-3">
                <span className="text-slate-700 font-bold">✗</span>
                <span className="text-gray-700">The service is provided on an <strong>"as is" and "as available"</strong> basis without any guarantees.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-slate-700 font-bold">✗</span>
                <span className="text-gray-700">We do not guarantee the tools will be error-free, uninterrupted, or suitable for every purpose.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-slate-700 font-bold">✗</span>
                <span className="text-gray-700">We are not liable for loss of data, profits, or other damages resulting from service use.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-slate-700 font-bold">✗</span>
                <span className="text-gray-700">We reserve the right to modify, suspend, or discontinue the service at any time.</span>
              </li>
            </ul>
          </div>
        </section>

        {/* Section 5 */}
        <section className="bg-white rounded-3xl p-8 md:p-12 shadow-md border border-orange-100">
          <div className="flex items-start gap-4 mb-6">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 mb-2">Limitation of Liability</h2>
              <p className="text-gray-600">Understanding our liability boundaries</p>
            </div>
          </div>

          <div className="ml-0 md:ml-16 bg-gradient-to-r from-gray-50 to-slate-50 rounded-2xl p-8 border border-gray-200">
            <p className="text-gray-700 leading-relaxed mb-4">
              To the fullest extent permitted by law, PDFConvert.tech shall not be liable for:
            </p>
            <ul className="space-y-2 text-gray-700">
              <li>• Any indirect, incidental, special, or consequential damages</li>
              <li>• Loss of data, revenue, or business interruption</li>
              <li>• Damages arising from third-party actions or services</li>
              <li>• Any damages exceeding the amount paid by you to use our service</li>
            </ul>
          </div>
        </section>

        {/* Section 6 */}
        <section className="bg-white rounded-3xl p-8 md:p-12 shadow-md border border-orange-100">
          <div className="flex items-start gap-4 mb-6">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 mb-2">Changes to Terms</h2>
              <p className="text-gray-600">How we handle updates to this agreement</p>
            </div>
          </div>

          <div className="ml-0 md:ml-16 bg-gradient-to-r from-green-50 to-emerald-50 rounded-2xl p-8 border border-green-100">
            <p className="text-gray-700 leading-relaxed mb-4">
              We may update these Terms of Service at any time without prior notice. Changes become effective immediately when posted on this page. Your continued use of the service after any changes indicates your acceptance of the updated terms.
            </p>
            <p className="text-gray-700 text-sm italic">
              We recommend reviewing these terms periodically to stay informed of any updates.
            </p>
          </div>
        </section>

        {/* Section 7 */}
        <section className="bg-white rounded-3xl p-8 md:p-12 shadow-md border border-orange-100">
          <div className="flex items-start gap-4 mb-6">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 mb-2">Contact & Disputes</h2>
              <p className="text-gray-600">How to reach us with questions or concerns</p>
            </div>
          </div>

          <div className="ml-0 md:ml-16 bg-gradient-to-r from-purple-50 to-pink-50 rounded-2xl p-8 border border-purple-100 text-center">
            <p className="text-gray-700 mb-6">
              If you have questions about these terms or disputes regarding the service, please contact us:
            </p>
            <div className="space-y-3">
              <p className="text-gray-700">
                <strong>Email:</strong> <a href="mailto:contact@pdfconvert.tech" className="text-orange-600 hover:text-orange-700 font-semibold">contact@pdfconvert.tech</a>
              </p>
            </div>
          </div>
        </section>

        {/* Last Updated */}
        <div className="text-center text-gray-600 text-sm mt-12 mb-6">
          <p>Last updated: December 2025</p>
          <p className="mt-1">This is provided for general information only and does not constitute legal advice.</p>
        </div>

      </div>

    </Layout>
  );
};

export default TermsPage;
